DROP TABLE IF EXISTS AACCOUNT;
CREATE TABLE AACCOUNT (
  IID int(36) NOT NULL AUTO_INCREMENT,
  NNAME varchar(255) DEFAULT NULL,
  PPASSWORD varchar(255) DEFAULT NULL,
  LLOCKEND_TIME varchar(40) DEFAULT NULL,
  LLOGIN_NUMBER int(11) DEFAULT '0',
  PPHONENUMBER varchar(40) DEFAULT NULL,
  EEMAIL varchar(255) DEFAULT NULL,
  DDESC varchar(255) DEFAULT NULL,
  CCREATE_TIME varchar(255) DEFAULT NULL,
  PRIMARY KEY (IID)
)DEFAULT CHARACTER SET UTF8;

DROP TABLE IF EXISTS ACCOUNT_RROLE_RELATION;
CREATE TABLE ACCOUNT_RROLE_RELATION (
  IID int(36) NOT NULL AUTO_INCREMENT,
  AACCOUNT_ID int(36) DEFAULT NULL,
  RROLE_ID int(36) DEFAULT NULL,
  PRIMARY KEY (IID)
)DEFAULT CHARACTER SET UTF8;

DROP TABLE IF EXISTS RROLE;
CREATE TABLE RROLE (
  IID int(36) NOT NULL AUTO_INCREMENT,
  NNAME varchar(255) DEFAULT NULL,
  DDESC varchar(255) DEFAULT NULL,
  CCODE int(11) DEFAULT NULL,
  CCREATE_TIME varchar(255) DEFAULT NULL,
  PRIMARY KEY (IID)
)DEFAULT CHARACTER SET UTF8;

DROP TABLE IF EXISTS RROLE_PERMISSION_RELATION;
CREATE TABLE RROLE_PERMISSION_RELATION (
  IID int(36) NOT NULL AUTO_INCREMENT,
  RROLE_ID int(36) DEFAULT NULL,
  PPERMISSION_ID int(36) DEFAULT NULL,
  PRIMARY KEY (IID)
)DEFAULT CHARACTER SET UTF8;

DROP TABLE IF EXISTS PPERMISSION;
CREATE TABLE PPERMISSION (
  IID int(36) NOT NULL AUTO_INCREMENT,
  NNAME varchar(255) DEFAULT NULL,
  DDESC varchar(255) DEFAULT NULL,
  CCODE int(11) DEFAULT NULL,
  PRIMARY KEY (IID)
)DEFAULT CHARACTER SET UTF8;

DROP TABLE IF EXISTS IP_MANAGEMENT;
CREATE TABLE IP_MANAGEMENT(
	IID INT AUTO_INCREMENT,
	AACCOUNT_NAME VARCHAR(1024),
	IIP VARCHAR(1024),
	NNETMASK VARCHAR(1024),
	PRIMARY KEY(IID)
)DEFAULT CHARACTER SET UTF8;
DROP TABLE IF EXISTS AADMIN_LOG;
create table  `ADMIN_LOG`(
       `IID`            BIGINT not null AUTO_INCREMENT comment '标识',
       `TTIME`     VARCHAR(32) comment '发生时间',
       `LLEVEL` INT comment '级别（成功或失败）',
       `AACCOUNT` VARCHAR(64) comment '用户',
       `IIP`     VARCHAR(64) comment 'IP地址',
       `DDESC`      VARCHAR(2048) comment '描述',
       `CCREATE_TIME`      VARCHAR(100) comment '创建时间',
		primary key (`IID`)
)DEFAULT CHARACTER SET UTF8;

DROP TABLE IF EXISTS SSYSCONFIG;
CREATE TABLE SSYSCONFIG (
	IID VARCHAR(127),
	NNAME VARCHAR(512),
	VVALUE VARCHAR(512),
	UUPDATE_TIME VARCHAR(32),
	PRIMARY KEY(IID)
) DEFAULT CHARACTER SET UTF8;

INSERT INTO AACCOUNT(NNAME,PPASSWORD,PPHONENUMBER,EEMAIL,CCREATE_TIME) VALUES ('admin', 'e10adc3949ba59abbe56e057f20f883e', '13521190254', '123@dsp.ac.cn', '2075/08/09 11:12:12');
INSERT INTO PPERMISSION(NNAME,DDESC,CCODE) VALUES ('账户管理', '账户管理', '10000');
INSERT INTO PPERMISSION(NNAME,DDESC,CCODE) VALUES ('配置管理', '配置管理', '20000');
INSERT INTO PPERMISSION(NNAME,DDESC,CCODE) VALUES ('转储会话', '转储会话', '30000');
INSERT INTO PPERMISSION(NNAME,DDESC,CCODE) VALUES ('审计日志', '审计日志', '40000');

INSERT INTO RROLE(NNAME,DDESC,CCODE) VALUES ('账户管理', '账户管理', '10000');
INSERT INTO RROLE(NNAME,DDESC,CCODE) VALUES ('配置管理', '配置管理', '20000');
INSERT INTO RROLE(NNAME,DDESC,CCODE) VALUES ('转储会话', '转储会话', '30000');
INSERT INTO RROLE(NNAME,DDESC,CCODE) VALUES ('审计日志', '审计日志', '40000');

INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('MAX_LOGIN_COUNT','锁定用户的登录次数门限','4','2014/09/11 09:35:05');
INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('UNLOCK_ACCOUNT_TIME','解锁时间（秒）','86460','2014/09/11 09:35:05');
INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('MAIL_SERVER_HOST','SMTP地址','smtp.163.com','2014/09/11 09:35:05');
INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('MAIL_SERVER_ACCOUNT','邮件服务器用户名','admin','2014/09/11 09:35:05');
INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('MAIL_SERVER_PASSWORD','邮件服务器密码','123456','2014/09/11 09:35:05');
INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('BOOK_FILE_ADDRESS','书籍上传的路径','/book/','2014/09/11 09:35:05');
INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('LUCENE_FILE_ADDRESS','LUCENE索引的路径','d:/lucene','2014/09/11 09:35:05');
INSERT INTO SSYSCONFIG(IID,NNAME,VVALUE,UUPDATE_TIME) VALUES('ILLEGAL_CHARACTER_NUMBER_TIME','非法字符出现的次数','3','2014/09/11 09:35:05');