DROP TABLE　IF EXISTS BBOOK;
DROP TABLE　IF EXISTS BBOOK_TEMPORARY;
CREATE TABLE BBOOK(
	IID BIGINT NOT NULL AUTO_INCREMENT,
	BBOOK_NAME VARCHAR(128),
	AAUTHOR_ID BIGINT,
	BBOOK_TYPE BIGINT,
	BBOOK_SYNOPSIS VARCHAR(2048) comment '书籍简介',
	BBOOK_FILE VARCHAR(128),
	CCREATE_TIME VARCHAR(40),
	MMODIFY_TIME VARCHAR(40)
);
CREATE TABLE BBOOK_TEMPORARY(
	IID BIGINT NOT NULL AUTO_INCREMENT,
	BBOOK_NAME VARCHAR(128),
	AAUTHOR_ID BIGINT,
	BBOOK_TYPE BIGINT,
	BBOOK_SYNOPSIS VARCHAR(2048) comment '书籍简介',
	IIS_CHECK BIGINT,
	ILLEGAL_CHARACTER BIGINT,
	BBOOK_FILE VARCHAR(128),
	CCREATE_TIME VARCHAR(40),
	MMODIFY_TIME VARCHAR(40)
);