
DROP TABLE IF EXISTS CCRM_CUSTOMER;
DROP TABLE IF EXISTS CCRM_SUB_CUSTOMER;
DROP TABLE IF EXISTS CCRM_SUB_CUSTOMER_RESOURCE;
DROP TABLE IF EXISTS CCRM_SUBSCRIBER;
DROP TABLE IF EXISTS CCRM_SUBSCRIBER_ITEM;
DROP TABLE IF EXISTS CCRM_ORDER;
DROP TABLE IF EXISTS CCRM_ORDER_ITEM;
DROP TABLE IF EXISTS CCRM_SUBSCRIBER_HISTORY;
DROP TABLE IF EXISTS CCRM_SUBSCRIBER_ITEM_HISTORY;
CREATE TABLE CCRM_CUSTOMER_KEY_GENERATOR(
	KKEY varchar(128),
	VVALUE BIGINT,
	PRIMARY KEY(KKEY)
);

CREATE TABLE CCRM_CUSTOMER(
	IID BIGINT,
	SSTATE varchar(60),
	IIDENTITY_TYPE INTEGER,
	IIDENTITY_NUMBER varchar(60),
	NNAME varchar(60),
	DDEFINED_ID varchar(40),
	PPASSWORD varchar(40),
	TTYPE INTEGER,
	LLEVEL INTEGER,
	CCREDIT_DEGREE INTEGER,
	PPHONE varchar(20),
	AADDRESS varchar(80),
	DDEFINED_ADDRESS varchar(80),
	CCREATE_TIME varchar(40),
	MMODIFY_TIME varchar(40),
	PPARENT_GROUP varchar(40),
	AALIAS varchar(100),
	GGENDER varchar(80),
	BBIRTH_DATE varchar(40),
	MMARRIED varchar(80),
	RRELIGION varchar(40),
	FFAVOURITE varchar(100),
	OOTHER_PHONE varchar(40),
	AADDRESS_ALIAS varchar(80),
	MMAIL_ADDR varchar(104),
	ZZIP varchar(60),
	LLINK_NAME varchar(24),
	NNEIGHBOR varchar(100),
	EEMAIL varchar(40),
	FFAX varchar(40),
	
	RREMARK varchar(1024),
	WWORK_UNIT varchar(100),
	UUNIT_KIND varchar(200),
	OOFFICE_PHONE varchar(60),
	JJOB_TYPE varchar(80),
	EEDUCATION_LEVEL varchar(200),
	IINCOME_LEVEL varchar(80),
	AAGENT_ID varchar(80),
	AACCOUNT_BANK varchar(200),
	AACCOUNT_NAME varchar(104),
	AACCOUNT_ID varchar(104),
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_CUSTOMER_KEY',100000);	

CREATE TABLE CCRM_SUB_CUSTOMER(
	IID BIGINT,
	SSTATE INTEGER,
	LLOGIN_NAME varchar(40),
	NNICK_NAME varchar(100),
	PPASSWORD varchar(40),
	MMODIFY_TIME varchar(40),
	CCUSTOMER_ID BIGINT,
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_SUB_CUSTOMER_KEY',100000);

CREATE TABLE CCRM_SUB_CUSTOMER_RESOURCE(
	IID BIGINT,
	RRESOURCE_ID varchar(40),
	SSUB_CUSTOMER_ID BIGINT,
	SSTATE INTEGER,
	MMODIFY_TIME varchar(40),
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_SUB_CUSTOMER_RESOURCE_KEY',100000);

CREATE TABLE CCRM_SUBSCRIBER(
	IID BIGINT,
	PPRODUCT_ID BIGINT,
	PPRODUCT_NAME varchar(100),
	SSTATE INTEGER,
	SSTART_TIME varchar(40),
	BBILLING_START_TIME varchar(40),
	BBILLING_END_TIME varchar(40),
	EEND_TIME varchar(40),
	SSTOP_TIME varchar(40),
	MMODIFY_TIME  varchar(40),
	SSUBCUSTOMER_ID BIGINT,
	RRENEWABLE BIGINT,
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_SUBSCRIBER_KEY',100000);

CREATE TABLE CCRM_SUBSCRIBER_ITEM(
	IID BIGINT,
	PPRODUCT_ITEM_ID BIGINT,
	PPRODUCT_ITEM_NAME varchar(100),
	SSTATE INTEGER,
	SSTART_TIME varchar(40),
	BBILLING_START_TIME varchar(40),
	BBILLING_END_TIME varchar(40),
	EEND_TIME varchar(40),
	SSTOP_TIME varchar(40),
	MMODIFY_TIME  varchar(40),
	SSUBSCRIBER_ID BIGINT,
	RRENEWABLE BIGINT,
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_SUBSCRIBER_ITEM_KEY',100000);

CREATE TABLE CCRM_ORDER(
	IID BIGINT,
	SSUB_SCRIBER_ID BIGINT,
	TTYPE INTEGER,
	PPRODUCT_ID BIGINT,
	PPRODUCT_NAME varchar(100),
	SSTATE INTEGER, 
	MMONTHS INTEGER, 
	TTRIGGER_TIME varchar(40),
	SSTART_TIME varchar(40),
	BBILLING_START_TIME varchar(40),
	BBILLING_END_TIME varchar(40),
	EEND_TIME  varchar(40),
	CCREATE_TIME varchar(40),
	MMODIFY_TIME varchar(40),
	SSUB_CUSTOMER_ID BIGINT,
	RRENEWABLE BIGINT,
	AACCEPTANCE_ID BIGINT,
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_ORDER_KEY',100000);

CREATE TABLE CCRM_ORDER_ITEM(
	IID BIGINT,
	OORDER_ID BIGINT,
	SSUB_SCRIBER_ITEM_ID BIGINT,
	PPRODUCT_ITEM_ID BIGINT,
	PPRODUCT_ITEM_NAME varchar(100),
	SSTART_TIME varchar(40),
	BBILLING_START_TIME varchar(40),
	BBILLING_END_TIME varchar(40),
	EEND_TIME  varchar(40),
	RRENEWABLE BIGINT,
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_ORDER_ITEM_KEY',100000);

CREATE TABLE CCRM_SUBSCRIBER_HISTORY(
	IID BIGINT,
	PPRODUCT_ID BIGINT,
	PPRODUCT_NAME varchar(100),
	SSTATE INTEGER,
	SSTART_TIME varchar(40),
	BBILLING_START_TIME varchar(40),
	BBILLING_END_TIME varchar(40),
	EEND_TIME varchar(40),
	SSTOP_TIME varchar(40),
	MMODIFY_TIME varchar(40),
	CCREATE_TIME varchar(40),
	SSUBCUSTOMER_ID BIGINT,
	RRENEWABLE BIGINT,
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_SUBSCRIBER_HISTORY_KEY',100000);

CREATE TABLE CCRM_SUBSCRIBER_ITEM_HISTORY(
	IID BIGINT,
	PPRODUCT_ITEM_ID BIGINT,
	PPRODUCT_ITEM_NAME varchar(100),
	SSTATE INTEGER,
	SSTART_TIME varchar(40),
	BBILLING_START_TIME varchar(40),
	BBILLING_END_TIME varchar(40),
	EEND_TIME varchar(40),
	SSTOP_TIME varchar(40),
	MMODIFY_TIME  varchar(40),
	SSUBSCRIBER_ID BIGINT,
	CCREATE_TIME varchar(40),
	SSUBSCRIBER_HISTORY_ID BIGINT,
	RRENEWABLE BIGINT,
	PRIMARY KEY(IID)
);

INSERT INTO CCRM_CUSTOMER_KEY_GENERATOR(KKEY,VVALUE) values('CCRM_SUBSCRIBER_ITEM_HISTORY_KEY',100000);